import type { Metadata } from 'next'
import { JetBrains_Mono as JetBrainsMono } from 'next/font/google'
import '@/styles/globals.css'

export const fontSans = JetBrainsMono({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} min-h-screen dark bg-gradient-to-br from-zinc-950 via-zinc-950/70 to-zinc-950/80 font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
